sudo: required
dist: bionic
language: go
go: "1.11"

branches:
  only:
  - master
  - /^v[0-9]/

services:
- docker

jobs:
  include:
  - stage: Tests
    name: "minishift"
    script: make release "IMAGE_TAG=test"

  - stage: Build and Deploy
    name: Build and Deploy to GitHub
    if: tag IS present
    before_script: skip
    script: make release "IMAGE_TAG=$TRAVIS_TAG"
    deploy:
      provider: releases
      api_key: "$GITHUB_TOKEN"
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file:
      - _out/*
      name: $TRAVIS_TAG
      on:
        tags: true
        branch: master
        repo: $TRAVIS_REPO_SLUG

addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools

cache:
  directories:
  - cache
  - "~/.minishift/cache"

before_script:
## FIXME Workaround for https://github.com/kubernetes/kubernetes/issues/61058
### And https://github.com/LiliC/travis-minikube/blob/e0f26f7b388057f51a0e2558afd5f990e07b6c49/.travis.yml#L11

