# WARNING! this manifest is not meant for direct consumption.
# you are supposed to deploy the operator either
# - through the HyperConverged Operator
# - using the released manifests, see github
# - using hack/install-operator.sh
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-ssp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevirt-ssp-operator
  template:
    metadata:
      labels:
        name: kubevirt-ssp-operator
    spec:
      serviceAccountName: kubevirt-ssp-operator
      strategy:
        type: Recreate
      containers:
        - name: kubevirt-ssp-operator
          image: quay.io/ksimon/kubevirt-ssp-operator-container
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_REFERENCE
              value: REPLACE_IMAGE
            - name: WATCH_NAMESPACE
              value: ""
            - name: KVM_INFO_TAG
              value: ""
            - name: VALIDATOR_TAG
              value: ""
            - name: VIRT_LAUNCHER_TAG
              value: ""
            - name: NODE_LABELLER_TAG
              value: ""
            - name: CPU_PLUGIN_TAG
              value: ""
            - name: IMAGE_NAME_PREFIX
              value: ""
            - name: OPERATOR_NAME
              value: "kubevirt-ssp-operator"
